### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by Lora048** [WildCodeSchool/RMT-2203-TeamKarma-lions#75]

**Comment by Lora048** [comment]
- [x] Container du calendrier qui s'adapte en fonction de la largeur de l'écran
- [x] vérifier media query image
- [ ] chargement des images 
- [ ]  **copier de Curiosity !**  le hover sur les boutons pour passer d'une page à l'autre (grossissement, couleur...)
